stages:
  - trigger

ui-pipeline:
  stage: trigger
  trigger:
    include:
      - local: 'plc-industrial-ui/.gitlab-ci.yml'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - plc-industrial-ui/**
        - plc-industrial-ui/**/*

query-pipeline:
  stage: trigger
  trigger:
    include:
      - local: 'plc-query-service/.gitlab-ci.yml'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - plc-query-service/**
        - plc-query-service/**/*
        
persist-pipeline:
  stage: trigger
  trigger:
    include:
      - local: 'plc-persist-service/.gitlab-ci.yml'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - plc-persist-service/**
        - plc-persist-service/**/*        
        
collector-pipeline:
  stage: trigger
  trigger:
    include:
      - local: 'plc-collector-service/.gitlab-ci.yml'
    strategy: depend
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - plc-collector-service/**
        - plc-collector-service/**/*                