spring:
  application:
    name: plc-collector-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:192.168.0.226:9092}
server:
  port: ${SERVER_PORT:8082}
plc:
  connection-string: "s7://${PLC:127.0.0.1}?controller-type=S7_300"
  poll-interval-ms: 1000
  auto-reconnect: true
  source: plc-simulator-1
  tags:
    - name: temperature
      address: "%DB90.DBW0:INT"   # DBW für 16-Bit Word, gefolgt vom PLC4X-Typ
    - name: pressure
      address: "%DB90.DBW2:INT"
    - name: level
      address: "%DB90.DBW4:INT"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
app:
  kafka:
    topics:
      plc-raw-readings: plc.raw.readings