/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { MeasurementHistoryPoint } from '../model/measurementHistoryPoint';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';
import {
    MeasurementHistoryControllerServiceInterface
} from './measurementHistoryController.serviceInterface';



@Injectable({
  providedIn: 'root'
})
export class MeasurementHistoryControllerService extends BaseService implements MeasurementHistoryControllerServiceInterface {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Load measurement history
     * @endpoint get /api/history/measurements
     * @param metric 
     * @param range 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public measurements(metric: 'TEMPERATURE' | 'PRESSURE' | 'LEVEL', range: 'LAST_5_MINUTES' | 'LAST_15_MINUTES' | 'LAST_1_HOUR' | 'LAST_24_HOURS', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<Array<MeasurementHistoryPoint>>;
    public measurements(metric: 'TEMPERATURE' | 'PRESSURE' | 'LEVEL', range: 'LAST_5_MINUTES' | 'LAST_15_MINUTES' | 'LAST_1_HOUR' | 'LAST_24_HOURS', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<Array<MeasurementHistoryPoint>>>;
    public measurements(metric: 'TEMPERATURE' | 'PRESSURE' | 'LEVEL', range: 'LAST_5_MINUTES' | 'LAST_15_MINUTES' | 'LAST_1_HOUR' | 'LAST_24_HOURS', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<Array<MeasurementHistoryPoint>>>;
    public measurements(metric: 'TEMPERATURE' | 'PRESSURE' | 'LEVEL', range: 'LAST_5_MINUTES' | 'LAST_15_MINUTES' | 'LAST_1_HOUR' | 'LAST_24_HOURS', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: 'application/json', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (metric === null || metric === undefined) {
            throw new Error('Required parameter metric was null or undefined when calling measurements.');
        }
        if (range === null || range === undefined) {
            throw new Error('Required parameter range was null or undefined when calling measurements.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'metric',
            <any>metric,
            QueryParamStyle.Form,
            true,
        );


        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'range',
            <any>range,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            'application/json'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/history/measurements`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<Array<MeasurementHistoryPoint>>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
