/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MeasurementHistoryPoint } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MeasurementHistoryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Load measurement history
     * 
     * @endpoint get /api/history/measurements
     * @param metric 
     * @param range 
     */
    measurements(metric: 'TEMPERATURE' | 'PRESSURE' | 'LEVEL', range: 'LAST_5_MINUTES' | 'LAST_15_MINUTES' | 'LAST_1_HOUR' | 'LAST_24_HOURS', extraHttpRequestParams?: any): Observable<Array<MeasurementHistoryPoint>>;

}
