/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PlcReadingEvent } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PlcQueryControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint delete /api/plc/{tag}
     * @param tag 
     */
    _delete(tag: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/plc/{tag}
     * @param tag 
     */
    get(tag: string, extraHttpRequestParams?: any): Observable<PlcReadingEvent>;

    /**
     * 
     * 
     * @endpoint get /api/plc
     */
    getAll(extraHttpRequestParams?: any): Observable<Array<PlcReadingEvent>>;

    /**
     * 
     * 
     * @endpoint post /api/plc
     * @param plcReadingEvent 
     */
    set(plcReadingEvent: PlcReadingEvent, extraHttpRequestParams?: any): Observable<PlcReadingEvent>;

}
