#logging:
#  level:
#    org.apache.kafka: ERROR

spring:
  application:
    name: plc-query-service
  datasource:
    url: jdbc:postgresql://postgres.cluster.lab:5432/plcdb
    username: plcuser
    password: plcpass
  jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:192.168.0.226}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:192.168.0.226:9092}
    consumer:
      group-id: plc-query-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.industrial.contracts.events"
        spring.json.value.default.type: com.example.industrial.contracts.events.PlcReadingEvent			
server:
  port: ${SERVER_PORT:8082}

app:
  kafka:
    topics:
      plc-raw-readings: plc.raw.readings

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true		